version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes
    
permissions:
   - object: /
     pattern: "**"
     owner: ec2-user
     group: ec2-user
  
hooks:
    AfterInstall:
      - location: stop.sh # nginx와 연결되어 있지 않은 스프링 부트 종료
        timeout: 60
        runas: ec2-user
    ApplicationStart:
      - location: start.sh # 새로 배포한 스프링부트 어플리케이션 실핸
        timeout: 60
        runas: ec2-user
    ValidateService:
      - location: health.sh # 새 스프링부트가 정상적으로  실행됐는지 확인
        timeout: 60
        runas: ec2-user